# .PHONY diz ao make que isso são comandos, não arquivos reais
.PHONY: run install migrate upgrade docker-up clean

# --- Comandos do Servidor ---

# Inicia o servidor em modo de desenvolvimento
run:
	npm run dev