"""Add credits to workspace

Revision ID: 557fc103f35d
Revises: f1b615dd6a27
Create Date: 2026-01-05 15:39:57.496763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557fc103f35d'
down_revision: Union[str, Sequence[str], None] = 'f1b615dd6a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('credits', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'credits')
    # ### end Alembic commands ###
