"""

Revision ID: 9201e8de9dba
Revises: 5cc1ea7473da
Create Date: 2026-01-06 13:43:50.208150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9201e8de9dba'
down_revision: Union[str, Sequence[str], None] = '5cc1ea7473da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill', sa.Enum('HARD', 'SOFT', name='typeskill'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='statusskill'), nullable=False),
    sa.Column('use', sa.Enum('REALEASED', 'PROCESSING', 'ERROR', name='useskill'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_created_at'), 'skills', ['created_at'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_skill'), 'skills', ['skill'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_index(op.f('ix_skills_status'), 'skills', ['status'], unique=False)
    op.create_index(op.f('ix_skills_workspace_id'), 'skills', ['workspace_id'], unique=False)
    op.create_table('skill_knowledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('FILE', 'WEBSITE', 'TEXT', 'YOUTUBE', name='sourcetype'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('s3_region', sa.String(length=50), nullable=True),
    sa.Column('s3_url', sa.String(length=2000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_knowledges_file_hash'), 'skill_knowledges', ['file_hash'], unique=False)
    op.create_index(op.f('ix_skill_knowledges_id'), 'skill_knowledges', ['id'], unique=False)
    op.create_index(op.f('ix_skill_knowledges_processing_status'), 'skill_knowledges', ['processing_status'], unique=False)
    op.create_index(op.f('ix_skill_knowledges_s3_key'), 'skill_knowledges', ['s3_key'], unique=False)
    op.create_index(op.f('ix_skill_knowledges_skill_id'), 'skill_knowledges', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_knowledges_source_type'), 'skill_knowledges', ['source_type'], unique=False)
    op.create_table('skill_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.Enum('PDF', 'VIDEO', 'AUDIO', 'IMAGE', name='materialtype'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_context', sa.Text(), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('s3_region', sa.String(length=50), nullable=True),
    sa.Column('s3_url', sa.String(length=2000), nullable=True),
    sa.Column('s3_presigned_url', sa.Text(), nullable=True),
    sa.Column('presigned_url_expires_at', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_s3_key', sa.String(length=1000), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_materials_file_hash'), 'skill_materials', ['file_hash'], unique=False)
    op.create_index(op.f('ix_skill_materials_id'), 'skill_materials', ['id'], unique=False)
    op.create_index(op.f('ix_skill_materials_material_type'), 'skill_materials', ['material_type'], unique=False)
    op.create_index(op.f('ix_skill_materials_presigned_url_expires_at'), 'skill_materials', ['presigned_url_expires_at'], unique=False)
    op.create_index(op.f('ix_skill_materials_s3_key'), 'skill_materials', ['s3_key'], unique=False)
    op.create_index(op.f('ix_skill_materials_skill_id'), 'skill_materials', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_materials_usage_count'), 'skill_materials', ['usage_count'], unique=False)
    op.create_table('skill_retrieval_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_size', sa.Integer(), nullable=False),
    sa.Column('child_chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('qdrant_collection_name', sa.String(length=255), nullable=False),
    sa.Column('advanced_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_retrieval_configs_id'), 'skill_retrieval_configs', ['id'], unique=False)
    op.create_index(op.f('ix_skill_retrieval_configs_skill_id'), 'skill_retrieval_configs', ['skill_id'], unique=True)
    op.create_table('skill_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('PARENT', 'CHILD', name='chunktype'), nullable=False),
    sa.Column('parent_chunk_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=False),
    sa.Column('qdrant_collection', sa.String(length=255), nullable=False),
    sa.Column('synced_to_qdrant', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('mdata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['skill_knowledges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['skill_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_chunks_chunk_type'), 'skill_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_skill_chunks_content_hash'), 'skill_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_skill_chunks_id'), 'skill_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_skill_chunks_knowledge_source_id'), 'skill_chunks', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('ix_skill_chunks_parent_chunk_id'), 'skill_chunks', ['parent_chunk_id'], unique=False)
    op.create_index(op.f('ix_skill_chunks_qdrant_point_id'), 'skill_chunks', ['qdrant_point_id'], unique=False)
    op.create_index(op.f('ix_skill_chunks_skill_id'), 'skill_chunks', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_chunks_synced_to_qdrant'), 'skill_chunks', ['synced_to_qdrant'], unique=False)
    op.create_table('skill_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['skill_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_usage_logs_id'), 'skill_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_skill_usage_logs_material_id'), 'skill_usage_logs', ['material_id'], unique=False)
    op.create_index(op.f('ix_skill_usage_logs_user_id'), 'skill_usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_usage_logs_user_id'), table_name='skill_usage_logs')
    op.drop_index(op.f('ix_skill_usage_logs_material_id'), table_name='skill_usage_logs')
    op.drop_index(op.f('ix_skill_usage_logs_id'), table_name='skill_usage_logs')
    op.drop_table('skill_usage_logs')
    op.drop_index(op.f('ix_skill_chunks_synced_to_qdrant'), table_name='skill_chunks')
    op.drop_index(op.f('ix_skill_chunks_skill_id'), table_name='skill_chunks')
    op.drop_index(op.f('ix_skill_chunks_qdrant_point_id'), table_name='skill_chunks')
    op.drop_index(op.f('ix_skill_chunks_parent_chunk_id'), table_name='skill_chunks')
    op.drop_index(op.f('ix_skill_chunks_knowledge_source_id'), table_name='skill_chunks')
    op.drop_index(op.f('ix_skill_chunks_id'), table_name='skill_chunks')
    op.drop_index(op.f('ix_skill_chunks_content_hash'), table_name='skill_chunks')
    op.drop_index(op.f('ix_skill_chunks_chunk_type'), table_name='skill_chunks')
    op.drop_table('skill_chunks')
    op.drop_index(op.f('ix_skill_retrieval_configs_skill_id'), table_name='skill_retrieval_configs')
    op.drop_index(op.f('ix_skill_retrieval_configs_id'), table_name='skill_retrieval_configs')
    op.drop_table('skill_retrieval_configs')
    op.drop_index(op.f('ix_skill_materials_usage_count'), table_name='skill_materials')
    op.drop_index(op.f('ix_skill_materials_skill_id'), table_name='skill_materials')
    op.drop_index(op.f('ix_skill_materials_s3_key'), table_name='skill_materials')
    op.drop_index(op.f('ix_skill_materials_presigned_url_expires_at'), table_name='skill_materials')
    op.drop_index(op.f('ix_skill_materials_material_type'), table_name='skill_materials')
    op.drop_index(op.f('ix_skill_materials_id'), table_name='skill_materials')
    op.drop_index(op.f('ix_skill_materials_file_hash'), table_name='skill_materials')
    op.drop_table('skill_materials')
    op.drop_index(op.f('ix_skill_knowledges_source_type'), table_name='skill_knowledges')
    op.drop_index(op.f('ix_skill_knowledges_skill_id'), table_name='skill_knowledges')
    op.drop_index(op.f('ix_skill_knowledges_s3_key'), table_name='skill_knowledges')
    op.drop_index(op.f('ix_skill_knowledges_processing_status'), table_name='skill_knowledges')
    op.drop_index(op.f('ix_skill_knowledges_id'), table_name='skill_knowledges')
    op.drop_index(op.f('ix_skill_knowledges_file_hash'), table_name='skill_knowledges')
    op.drop_table('skill_knowledges')
    op.drop_index(op.f('ix_skills_workspace_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_status'), table_name='skills')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_created_at'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
